### ISSUE TITLE
If CUSTOM_ANNOTATION is enabled in environment and annotation check is set to false then experiment need not be triggered

### ISSUE THREAD

**Issue by vijayto** [litmuschaos/chaos-operator#262]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: FEATURE REQUEST

  Hey @ksatchit  just curious as per this chaos operator code, we could see that if the annotationcheck is enabled then only we could see that custom_annotaion is being honored as per this code snippet
```
if engine.Instance.Spec.AnnotationCheck == "true" {
		// Determine whether apps with matching labels have chaos annotation set to true
		engine, err = resource.CheckChaosAnnotation(engine, clientSet, *dynamicClient)
		if err != nil {
			r.recorder.Eventf(engine.Instance, corev1.EventTypeWarning, "ChaosResourcesOperationFailed", "Unable to get chaosengine")
			chaosTypes.Log.Info("Annotation check failed with", "error:", err)
			return err
		}
	} 
```
I was thinking - even if its set to false / not set, if we have CUSTOM_ANNOTATION environment variable set , then we should check deployment and skip chaos experiment on pod . Just a thought , what do you think

**Comment by sumitnagal** [comment]
We need to think about below cases, this assume we have given custom annotation as part of operator setup, below changes require for application and in custom resource.  check this PR as attempt to fix https://github.com/litmuschaos/chaos-operator/pull/263 

-  Annotation define flag True -> execute the chaos 

- Annotation define flag false -> don't execute the chaos 

- Annotation is not define flag false -> don't execute the chaos 


- 

With This we will be able to

**Comment by ksatchit** [comment]
This is the current expected behaviour: 


.spec.annotationCheck property (ChaosEngine CR)  (default key: litmuschaos.io/chaos) | Custom Annotation Defined (Operator ENV) | Annotation's Value(user defined) | Behaviour
-- | -- | -- | --
(This spec attribute is of type `omitempty`, i.e., an optional field. Set to True by default) |   |   |  
TRUE | N/A | TRUE | Inject Chaos
TRUE | N/A | FALSE | Skip Chaos
TRUE | DEFINED | TRUE | Inject Chaos
TRUE | DEFINED | FALSE | Skip Chaos
FALSE | N/A | N/A | Inject Chaos based on pod labels

**Comment by uditgaurav** [comment]
Here are the logs of the operator for `case-3` and `case-4`:

## Case-3

This is the current expected behavior (hope we are on the same page wrt this).
.spec.annotationCheck property (ChaosEngine CR)  (default key: litmuschaos.io/chaos) | Custom Annotation Defined (Operator ENV) | Annotation's Value (user defined) | Behaviour
-- | -- | -- | --
(This spec attribute is of type `omitempty`. Set to True by default) |   |   |  
TRUE | DEFINED | TRUE | Inject Chaos

- ### Logs:  [case-3.txt](https://github.com/litmuschaos/chaos-operator/files/5182749/case-3.txt)

---
## Case-4

This is the current expected behavior (hope we are on the same page wrt this).
.spec.annotationCheck property (ChaosEngine CR)  (default key: litmuschaos.io/chaos) | Custom Annotation Defined (Operator ENV) | Annotation's Value (user defined) | Behaviour
-- | -- | -- | --
(This spec attribute is of type `omitempty`. Set to True by default) |   |   |  
TRUE | DEFINED | FALSE | Skip Chaos

- ### Logs:  [case-4.txt](https://github.com/litmuschaos/chaos-operator/files/5182750/case-4.txt)

**Comment by sumitnagal** [comment]
As I suggested @ksatchit , if we define the Annotation at operator level there is no way we can override .. so below condition has to be added in your table, please add and let me know the desire behavior 
FALSE -- DEFINED -- True  - skip
FALSE - DEFINED - FALSE - skip

**Comment by ksatchit** [comment]
Based on discussed with @sumitnagal: 

- This enhancement was proposed as a deterrent to possible mistaken/false assumptions by developers that `false` flag on `.spec.annotationCheck` means chaos won't be performed, whereas it just does the opposite. 
- We can resolve this by just dropping this attribute `.spec.annotationCheck` from the ChaosEngine definition altogether. It is an optional parameter today, defaulting to "true". In essence, this means that folks only have to worry about the annotation Key (with `litmuschaos.io/chaos` OR custom ones like `intuit.chaos/enabled`) being set to `true` or `false` in the AUT (application under test) to control the occurrence of chaos. 
- This approach was agreed to be better than defining a separate filter policy for cases where custom annotations are defined

**Comment by ksatchit** [comment]
Closing the above issue & PR https://github.com/litmuschaos/chaos-operator/pull/263 on the basis of the above discussions.
